### PR TITLE
Add support show color near line number

### LINKED ISSUE #44: Implement show color near number line
Implement show color from the code near number line.

### PR DESCRIPTION
**Pull request by VovaStelmashchuk**
Close #44.

[x] Support color format `#FFFFFF`
[ ] Suport color [1, 1, 1]

### CODE REVIEW

**Comment by VovaStelmashchuk** [comment]
@ldenisey  Can I use Kotlin for write new features?

**Comment by ldenisey** [comment]
Hello @VovaStelmashchuk , sure Kotlin is fine.

**Comment by VovaStelmashchuk** [comment]
@ldenisey I cannot implement `setColorTo` at the moment, can you review current change and merge into main repository. I will implement the feature of setting color in future :)

**Comment by ldenisey** [comment]
Done, thanks for your PR.

**Pull request merged**
