### PR TITLE
Formatting, external OpenSCAD calls, IDEA version upgrade

### PR DESCRIPTION
**Pull request by ldenisey**
Hello,

I have done some improvements on your plugin.
I have added the formatting, external calls to open OpenSCAD and generated stl, png and svg, fixed a few deprecated calls.
Tested on version 192 and 193 Windows.
I merged your development branch.

### CODE REVIEW

**Comment by ncsaba** [comment]
Hi there,

Wow, you did an extensive job in improving the plugin.

I had to take a break on it after spending considerable amount of time
trying to implement true include beaviour like in the original
OpenaSCAD - but failed, as it seems there is no way to do that as an
Idea plugin developer. If you don't know exactly what I'm talking
about: includes as implemented now in the grammar will only work in
places where keywords are expected, but in original OpenSCAD you can
place them anywhere. In principle you could include a parameter list of
a module, it works (tested myself). You can place that include anywhere
after a space - and the grammar is parsed _after_ the file is included,
which we can't replicate in the Idea grammar...

But that was not the reason I stopped working on this, real life got in
between, and I had a very busy year.

I was just about to pick it up again - your timing is perfect :-)

Do you care to have a talk (slack/skype/whatever) and do some code
review together ? You do have extensive changes, and I would like to
understand them and be able to add some new code myself again.

Thanks for your efforts, maybe we can continue on this as a team, that
would certainly make maintenance easier !

Cheers,
Csaba

**Comment by ldenisey** [comment]
Hello,

Sure, we can have a talk. I used to have a slack account, will try and connect. What is you time zone ?
By the way, I am working on completion now, should be ready soon.
To be true, I was just starting to learn OpenSCAD language for some 3D projects I want to be parametric, I could not resign developing with a notepad-like editor :-) Anyway, I am not aware of this includes usage. Do you have an example ?

**Comment by ncsaba** [comment]
I'm located in Germany, so my time zone is Europe/Berlin.

I created a space named javampire on slack, if you send me a mail to
ncsaba@javampire.com I will send an invite to your email address for
that slack work-space. On github I can't see your mail address...

Cheers,
Csaba

**Comment by ldenisey** [comment]
Added Completion and code style configuration. I think I am done with it :-)

**Pull request closed without merging**
